Create botinfo.ts
MARCROCK22/zenitsu pull request #32
Opened 2021-05-14 14:03 UTC by MrRojito-Dev

no le sé al TS 😪

2021-05-15 04:59 UTC, Monoverde888 commented
no le sabes al shitpost

2021-06-02 23:34 UTC, VyrekXD requested changes

2021-06-02 23:34 UTC, VyrekXD commented on src/commands/bot/botinfo.ts
> +    async run({ client, message, langjson }: commandinterface): Promise<eris.Message> {
Para que importas langjson si nisiquiera estas haciendolo en español e ingles.

2021-06-02 23:46 UTC, MARCROCK22 commented on src/commands/bot/botinfo.ts
> +    async run({ client, message, langjson }: commandinterface): Promise<eris.Message> {
pq no le sabeal shitpost

2021-06-03 04:13 UTC, MrRojito-Dev commented on src/commands/bot/botinfo.ts
> +    async run({ client, message, langjson }: commandinterface): Promise<eris.Message> {
nolese

2021-07-31 02:08 UTC, closed without merging